 
cc_library(
    name= 'gate',
    incs = ['/www/src/gmsrv/skynet/service-src', '/www/src/gmsrv/skynet/service-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['service_gate.c'],  
    deps = ['#pthread', '#dl', '//skynet-src:skynet'],
    defs=['_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    optimize='O2'
)

cc_library(
    name= 'harbor',
    incs = ['/www/src/gmsrv/skynet/service-src', '/www/src/gmsrv/skynet/service-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['service_harbor.c'],  
    deps = ['#pthread', '#dl', '//skynet-src:skynet'],
    defs=['_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    optimize='O2'
)

cc_library(
    name= 'snlua',
    incs = ['/www/src/gmsrv/skynet/service-src', '/www/src/gmsrv/skynet/service-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['service_snlua.c'],  
    deps = ['#pthread', '#dl', '//skynet-src:skynet'],
    defs=['_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    optimize='O2'
)

cc_library(
    name= 'logger',
    incs = ['/www/src/gmsrv/skynet/service-src', '/www/src/gmsrv/skynet/service-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['service_logger.c'],  
    deps = ['#pthread', '#dl', '//skynet-src:skynet'],
    defs=['_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    optimize='O2'
)


