 
cc_library(
    name = 'lpeg',
    incs = ['/www/src/gmsrv/skynet/3rd/lpeg', '/www/src/gmsrv/skynet/3rd/lpeg/include', '/www/src/gmsrv/skynet/3rd/lua'],
    srcs = ['lpcode.c', 'lpvm.c', 'lptree.c', 'lpprint.c', 'lpcap.c'],  
    deps = ['#pthread', '#dl', '//3rd/lua:lua'],
    defs=[],
    extra_libs= [],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    optimize='O2'
)


