 
cc_library(
    name = 'lua-md5',
    incs = ['/www/src/gmsrv/skynet/3rd/lua-md5', '/www/src/gmsrv/skynet/3rd/lua-md5/include', '/www/src/gmsrv/skynet/3rd/lua'],
    srcs = ['md5lib.c', 'md5.c', 'compat-5.2.c'],  
    deps = ['#pthread', '#dl', '//3rd/lua:lua'],
    defs=[],
    extra_libs= [],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    optimize='O2'
)


