 
cc_library(
    name = 'amoeba',
    incs = ['/www/src/gmsrv/skynet/3rd/amoeba', '/www/src/gmsrv/skynet/3rd/amoeba/include', '/www/src/gmsrv/skynet/3rd/lua'],
    srcs = [ 'lua_amoeba.c'],  
    deps = ['#pthread', '#dl', '//skynet-src:skynet', '//3rd/lua:lua'],
    defs=[],
    extra_libs= [],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    optimize='O2'
)


