 
cc_library(
    name = 'skynet',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-skynet.c', 'lua-seri.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'cluster',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-cluster.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'bson',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-bson.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'sharedata',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-sharedata.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'stm',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-stm.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'multicast',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-multicast.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'debugchannel',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-debugchannel.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'clientsocket',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-clientsocket.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'mongo',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-mongo.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'mysqlaux',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-mysqlaux.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'socketdriver',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-socket.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'crypt',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-crypt.c', 'lsha1.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'memory',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-memory.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'profile',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-profile.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'netpack',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-netpack.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)


 
cc_library(
    name = 'seri',
    incs = ['/www/src/gmsrv/skynet/lualib-src', '/www/src/gmsrv/skynet/lualib-src/include', '/www/src/gmsrv/skynet/3rd/lua', '/www/src/gmsrv/skynet/skynet-src'],
    srcs = ['lua-seri.c'],
    deps = ['#pthread', '#dl', '//skynet/3rd/lua:lua', '//skynet/skynet-src:skynet'],
    defs=['_MT', '_GNU_SOURCE', '_REENTRANT'],
    export_incs=[],
    warning=[],
    extra_cppflags=[],
    extra_linkflags=[],
    link_all_symbols=True,
    optimize='O2'
)

